loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Insert.as_view(), name='insert'),
    # path('register/', views.Register.as_view(), name='register'),
    path('update/', views.Update.as_view(), name='update'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('delete/<int:pk>', views.PerfilDeleteView.as_view(), name='delete'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ProdutoList.as_view(), name='lista'),
    path('<slug>', views.ProdutoDetalhes.as_view(), name='produtoDetalhes'),
    path('ProdutoAddToCar/', views.ProdutoAddToCar.as_view(), name='produtoAddToCar'),
    path('ProdutoRemoverFromCar/', views.ProdutoRemoverFromCar.as_view(),
         name='produtoRemoverFromCar'),
    path('Cart/', views.Cart.as_view(), name='cart'),
    path('Resumo/', views.Resumo.as_view(), name='resumo'),
]

templates/partials/_carrinho.html
{% load static %}

{% load omfilters %}


<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
            <th>Ações</th>

        </tr>

        {% for item in request.session.carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{item.imagem}} ">
            </td>
            <td>
                <a href=" {% url 'produto:produtoDetalhes' item.slug %} ">
                    {{item.produto_nome}}
                </a>

            </td>
            <td>{{item.variacao_nome}}</td>
            <td>
                {{item.quantidade}}x
                {% if item.preco_unitario_promocional %}
                {{item.preco_unitario_promocional|filter_price}}
                {% else %}
                {{item.preco_unitario|filter_price}}
                {% endif %}
            </td>

            {% if item.preco_unitario_promocional %}
            <td> {{item.preco_quantitativo_promocional|filter_price}} </td>
            {% else %}
            <td> {{item.preco_quantitativo|filter_price}} </td>
            {% endif %}
            <td>
                <a class="ml-3" href=" {% url 'produto:produtoRemoverFromCar'%}?vid={{item.variacao_id}} ">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

templates/partials/_footer.html
<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Claudio Morais</span>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/partials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static '/assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static '/assets/custom/css/style.css' %}">

templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/_nav.html
{% load omfilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'produto:lista' %} ">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Olá, {{request.user.get_full_name}}
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                    <a class="dropdown-item" href="#">Meus Pedidos</a>

                    <a class="dropdown-item" href="{%url 'perfil:insert'%} ">Meus Dados</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'perfil:logout' %} ">Sair</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:login'%} ">Entrar</a>
            </li>
            {% endif %}


            {% if request.session.carrinho %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'produto:cart' %} ">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>
                            {{request.session.carrinho|cart_qtd_total}}x
                        </strong>


                    </span>
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/partials/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}

            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
            </li>
            {% endif %}
    </ul>
</div>
{% endif %}

templates/partials/_scripts.html
{% load static %}
<script src="{% static '/assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static '/assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static '/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static '/assets/font-awesome/js/all.js' %}"></script>
<script src="{% static '/assets/custom/js/scripts.js' %}"></script>