loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Insert.as_view(), name='insert'),
    # path('register/', views.Register.as_view(), name='register'),
    path('update/', views.Update.as_view(), name='update'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('delete/<int:pk>', views.PerfilDeleteView.as_view(), name='delete'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ProdutoList.as_view(), name='lista'),
    path('<slug>', views.ProdutoDetalhes.as_view(), name='produtoDetalhes'),
    path('ProdutoAddToCar/', views.ProdutoAddToCar.as_view(), name='produtoAddToCar'),
    path('ProdutoRemoverFromCar/', views.ProdutoRemoverFromCar.as_view(),
         name='produtoRemoverFromCar'),
    path('Cart/', views.Cart.as_view(), name='cart'),
    path('Resumo/', views.Resumo.as_view(), name='resumo'),
]

perfil/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models
from datetime import date

# class UpdateUserForm(forms.ModelForm):
#     # password = forms.CharField(
#     #     required=False,
#     #     label='Senha',
#     #     widget=forms.PasswordInput()
#     # )

#     # confirm_password = forms.CharField(
#     #     required=False,
#     #     label='Confirmar Senha',
#     #     widget=forms.PasswordInput()
#     # )

#     class Meta:
#         model = User
#         fields = ('first_name', 'last_name', 'email', 'username')

# class UserForm(forms.ModelForm):
#     password = forms.CharField(
#         required=True,
#         label='Senha',
#         widget=forms.PasswordInput()
#     )

#     confirm_password = forms.CharField(
#         required=True,
#         label='Confirmar Senha',
#         widget=forms.PasswordInput()
#     )

#     class Meta:
#         model = User
#         fields = ('first_name', 'last_name', 'email', 'username',
#                   'password', 'confirm_password')

#     def clean(self, *args, **kwargs):

#         cleaned = self.cleaned_data
#         fields_validation_error = {}

#         first_name_data = cleaned.get('first_name')
#         last_name_data = cleaned.get('last_name')
#         email_data = cleaned.get('email')
#         username_data = cleaned.get('username')
#         password_data = cleaned.get('password')
#         confirm_password_data = cleaned.get('confirm_password')

#         error_email_exists = 'Email jah cadastrado'
#         error_user_exists = 'Usuario jah cadastrado'
#         error_password_short = 'Senha precisa ser maios que 8 digitos'
#         error_password_math = 'Senhas não conferem'
#         error_password_null = 'Campo Obrigatório'

#         email_db = User.objects.filter(email=email_data).first()
#         user_db = User.objects.filter(username=username_data).first()

#         if user_db:
#             fields_validation_error['username'] = error_user_exists

#         if email_db:
#             fields_validation_error['email'] = error_email_exists

#         if password_data:
#             if password_data != confirm_password_data:
#                 fields_validation_error['confirm_password'] = error_password_math
#             if len(password_data) < 8:
#                 fields_validation_error['password'] = error_password_short

#         if fields_validation_error:
#             raise(forms.ValidationError(fields_validation_error))


# class PerfilForm(forms.ModelForm):

#     class Meta:
#         model = Perfil
#         fields = ("__all__")
#         exclude = ('usuario',)

#     def clean(self, *args, **kwargs):
#         cleaned = self.cleaned_data
#         cpf_data = cleaned.get('cpf')
#         idade_data = cleaned.get('idade')
#         dt_nascimento_data = cleaned.get('data_nascimento')
#         dt_atual = date.today()
#         fields_error_validate = {}

#         cpf_db = Perfil.objects.filter(cpf=cpf_data).first()

#         # # verifica se o cpf jah está cadastrado
#         # if cpf_db:
#         #     fields_error_validate['cpf'] = 'CPF jah Cadastrado'

#         # verifica se a idade correponde a data de nascimento
#         # idade = abs((dt_atual.year - dt_nascimento_data.year))
#         # if idade != idade_data:
#         #     fields_error_validate[
#         #         'data_nascimento'] = f'Idade não corresponde a data de nascimento, idade{idade}'

#         if fields_error_validate:
#             raise (forms.ValidationError(fields_error_validate))


class PerfilForm(forms.ModelForm):
    class Meta:
        model = models.Perfil
        fields = '__all__'
        exclude = ('usuario',)


class UserForm(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha',
    )

    password2 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirmação senha'
    )

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.usuario = usuario

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password',
                  'password2', 'email')

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        usuario_data = cleaned.get('username')
        email_data = cleaned.get('email')
        password_data = cleaned.get('password')
        password2_data = cleaned.get('password2')

        usuario_db = User.objects.filter(username=usuario_data).first()
        email_db = User.objects.filter(email=email_data).first()

        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'E-mail já existe'
        error_msg_password_match = 'As duas senhas não conferem'
        error_msg_password_short = 'Sua senha precisa de pelo menos 6 caracteres'
        error_msg_required_field = 'Este campo é obrigatório.'

        # Usuários logados: atualização
        if self.usuario:
            if usuario_db:
                if usuario_data != usuario_db.username:
                    validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                if email_data != email_db.email:
                    validation_error_msgs['email'] = error_msg_email_exists

            if password_data:
                if password_data != password2_data:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password2'] = error_msg_password_match

                if len(password_data) < 6:
                    validation_error_msgs['password'] = error_msg_password_short

        # Usuários não logados: cadastro
        else:
            if usuario_db:
                validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                validation_error_msgs['email'] = error_msg_email_exists

            if not password_data:
                validation_error_msgs['password'] = error_msg_required_field

            if not password2_data:
                validation_error_msgs['password2'] = error_msg_required_field

            if password_data != password2_data:
                validation_error_msgs['password'] = error_msg_password_match
                validation_error_msgs['password2'] = error_msg_password_match

            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_short

        if validation_error_msgs:
            raise(forms.ValidationError(validation_error_msgs))

perfil/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.utils import timezone
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import DeleteView
from django.contrib.auth.models import User
from . import models, forms
from external.api import Api
import copy


class Insert(View):

    template_name = 'perfil/insert_user.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.carrinho = copy.deepcopy(self.request.session.get('carrinho', {}))

        self.perfil = None

        if self.request.user.is_authenticated:
            self.perfil = models.Perfil.objects.filter(
                usuario=self.request.user
            ).first()

            self.contexto = {
                'userform': forms.UserForm(
                    data=self.request.POST or None,
                    usuario=self.request.user,
                    instance=self.request.user,
                ),
                'perfilform': forms.PerfilForm(
                    data=self.request.POST or None,
                    instance=self.perfil
                )
            }
        else:
            self.contexto = {
                'userform': forms.UserForm(
                    data=self.request.POST or None
                ),
                'perfilform': forms.PerfilForm(
                    data=self.request.POST or None
                )
            }

        self.userform = self.contexto['userform']
        self.perfilform = self.contexto['perfilform']

        if self.request.user.is_authenticated:
            self.template_name = 'perfil/atualizar.html'

        self.renderizar = render(
            self.request, self.template_name, self.contexto
        )

    def get(self, *args, **kwargs):
        return self.renderizar

    def post(self, *args, **kwargs):
        if not self.userform.is_valid() or not self.perfilform.is_valid():
            messages.error(
                self.request,
                'Existem erros no formulário de cadastro. Verifique se todos '
                'os campos foram preenchidos corretamente.'
            )

            return self.renderizar

        username = self.userform.cleaned_data.get('username')
        password = self.userform.cleaned_data.get('password')
        email = self.userform.cleaned_data.get('email')
        first_name = self.userform.cleaned_data.get('first_name')
        last_name = self.userform.cleaned_data.get('last_name')

        # Usuário logado (atualiza)
        if self.request.user.is_authenticated:
            usuario = get_object_or_404(
                User, username=self.request.user.username)

            usuario.username = username

            if password:
                usuario.set_password(password)

            usuario.email = email
            usuario.first_name = first_name
            usuario.last_name = last_name
            usuario.save()

            """
            verifica se usuário logado tem perfil criado
            se não tiver, pega os dados do formaulzario de perfil
            e grava no banco passado o usuario_id
            """
            if not self.perfil:
                self.perfilform.cleaned_data['usuario'] = usuario
                print(self.perfilform.cleaned_data)
                perfil = models.Perfil(**self.perfilform.cleaned_data)
                perfil.save()
            else:
                perfil = self.perfilform.save(commit=False)
                perfil.usuario = usuario
                perfil.save()

            """
            Implementação da API- methodo PUT
            """

            api = Api()
            return_api = api.isGetCliente()
            return_end = api.isGetEndereco()

            # obtem o id da lista de dicionários
            self.id_user = None
            for item in return_api:
                if item['code'] == str(usuario.id):
                    self.id_user = item.get('id')
                    break

            # obtem id do endereço
            self.id_endereco = None
            for item in return_end:
                if item['code'] == str(perfil.id):
                    self.id_endereco = item.get('id')
                    break

            self.data = {
                "id": self.id_user,
                "name": f'{usuario.first_name} {usuario.last_name}',
                "code": usuario.id,
                "cpf": perfil.cpf,
                "email": usuario.email,
                "fone": perfil.fone,
                "create_at": "2021-03-17T20:46:46-03:00",
                "endereco": [
                    self.id_endereco
                ]
            }

            # exucuta o PUT na api
            api.isPutCliente(self.data, self.id_user)

        # Usário não logado (novo)
        else:

            usuario = self.userform.save(commit=False)
            usuario.set_password(password)
            usuario.save()

            perfil = self.perfilform.save(commit=False)
            perfil.usuario = usuario
            perfil.save()

            """
            
            Implementação da API- methodo POST
            Executa metodo post da api
            apos gravar dados no banco local,
            faz um POST na api
            http://127.0.0.1:8000/api/apiendereco/ e
            http://127.0.0.1:8000/api/apiclientes/

            """
            api = Api()

            self.data_endereco = {
                "id": perfil.id,
                "code": perfil.id,
                "street": perfil.endereco,
                "number": perfil.numero,
                "complement": perfil.complemento,
                "district": perfil.bairro,
                "city": perfil.cidade,
                "state": perfil.estado,
                "zip_code": perfil.cep,
                "delivery": True
            }

            return_api_josn = api.isPostEndereco(self.data_endereco)
            # print('resultado da api endereco')
            # print(return_api_josn)
            str_create_at = usuario.date_joined.strftime('%Y-%m-%dT%H:%M:%S')

            if return_api_josn:
                self.data_cliente = {
                    "id": perfil.id,
                    'name': f'{usuario.first_name} {usuario.last_name}',
                    "code": usuario.id,
                    "cpf": perfil.cpf,
                    "email": usuario.email,
                    "fone": perfil.fone,
                    "create_at": str_create_at,
                    "endereco": [return_api_josn.get('id')]
                }

                api.isPostCliente(self.data_cliente)

        # faz login do usuário
        if password:
            autentica = authenticate(
                self.request,
                username=usuario,
                password=password
            )

            if autentica:
                login(self.request, user=usuario)

        self.request.session['carrinho'] = self.carrinho
        self.request.session.save()

        messages.success(
            self.request,
            'Seu cadastro foi criado ou atualizado com sucesso.'
        )

        return redirect('produto:cart')
        return self.renderizar


class Register(Insert):
    pass


class Update(View):
    def get(self, *args, **kwargs):
        return HttpResponse('Atualizar')


class Login(View):
    def get(self, *args, **kwargs):
        return redirect('perfil:insert')

    def post(self, request, *args, **kwargs):
        user = self.request.POST.get('usuario')
        senha = self.request.POST.get('senha')

        if not user or not senha:
            messages.error(self.request, 'Usuário e senha invalidos')
            return redirect('perfil:login')

        usuario = authenticate(self.request, username=user, password=senha)

        if not usuario:
            messages.error(self.request, 'Usuário e senha invalidos')
            return redirect('perfil:login')
        login(self.request, user=usuario)
        return redirect('produto:lista')


class Logout(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        return redirect('produto:lista')


class PerfilDeleteView(DeleteView):
    model = models.User
    template_name = "perfil/delete.html"
    context_object_name = 'usuario'

    def get_success_url(self):
        usuario = self.get_object()

        """
        executa metodo GET para obter o id do cliente
        """
        api = Api()
        return_api = api.isGetCliente()

        # obtem o id da lista de dicionários
        self.id_user = None
        for item in return_api:
            if item['code'] == str(usuario.id):
                self.id_user = item.get('id')
                break

        api.isDeleteCliente(self.id_user)

        messages.success(
            self.request, f": (- sentiremos sua falta {usuario.first_name} {usuario.last_name}"
        )
        return reverse_lazy("produto:lista")

perfil/templates/perfil/atualizar.html
{% extends 'perfil/insert_user.html' %}

{% block titulo %}Atualizar perfil de {{ user }} | {% endblock %}

{% block titulocadastro %}
<h4>Atualizar cadastro</h4>
<p>
    Utilize o formulário a seguir para atualizar seus dados.
</p>
{% endblock %}

perfil/templates/perfil/delete.html
{% extends 'base.html' %}
{% load omfilters %}

<!-- {% block titulo %}Resumo da compra | {% endblock %} -->

{% block 'content' %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Ops!!! Tem certeja que deseja apagar sua conta?</h2>

        <p class="lead">Seus dados</p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ usuario.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ usuario.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.idade }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.data_nascimento }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ usuario.email }}</dd>
        </dl>
        <div class="row">
            <div class="col">
                <form action="{% url 'perfil:delete' request.user.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" value='delete' class="btn btn-block btn-lg btn-danger">
                        Sim, Tenho certeza
                    </button>
                    <a type="button" class="btn btn-block btn-lg btn-success" href="{% url 'produto:lista' %}">
                        Não, Me leve de volta
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

perfil/templates/perfil/insert_user.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block 'content' %}

<div class="row">
    {% if not request.user.is_authenticated %}

    <div class="col-lg">



        <h4>Login</h4>

        <form action="{% url 'perfil:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Usuário</label>
                <input type="text" class="form-control" id="username" name='usuario' aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="password">Senha</label>
                <input type="password" class="form-control" id="password" name="senha">
            </div>
            <button type="submit" class="btn btn-primary">Acessar</button>
        </form>
    </div>


    <div class="col-lg">
        <h4>Criar conta</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{userform|crispy}}
            {{perfilform|crispy}}
            <div class="row">
                <div class="col-lg">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Enviar</button>
                </div>
            </div>
        </form>

    </div>
    {% else %}
    <div class="col-lg">
        <h4>Atualizar dados</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{userform|crispy}}
            {{perfilform|crispy}}
            <div class="row">
                <div class="col-lg">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Enviar</button>
                    <a href="{% url 'perfil:delete' request.user.id %} " class="btn btn-danger btn-block btn-lg">Apagar
                        Conta</a>

                </div>
            </div>
        </form>

        {% endif %}

    </div>

    {% endblock 'content' %}

perfil/templates/perfil/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block 'content' %}
<!-- 
<div class="row">

    <div class="col-lg">
        {% if request.user.is_authenticated %}
        <h1>Atualizar dados</h1>
        {%else%}
        <h1>Cadastro</h1>
        {% endif %}

        <form action="" method="POST">
            {% csrf_token %}
            {{perfilform|crispy}}
            <div class="row">
                <div class="col-lg">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Register</button>
                </div>
            </div>
        </form>

    </div>

</div> -->

{% endblock 'content' %}

perfil/templates/perfil/update_user.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block 'content' %}
<form action="" method="POST">
    {% csrf_token %}
    {{userform|crispy}}
    {{perfilform|crispy}}
    <div class="row">
        <div class="col-lg">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Salvar</button>
        </div>
    </div>
</form>
{% endblock 'content' %}