loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/', views.Pagar.as_view(), name='pagar'),
    path('salvarPedido/', views.SalvarPedido.as_view(), name='salvarPedido'),
    path('detalhePedido/<int:pk>',
         views.DetalhePedido.as_view(), name='detalhePedido'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Insert.as_view(), name='insert'),
    # path('register/', views.Register.as_view(), name='register'),
    path('update/', views.Update.as_view(), name='update'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('delete/<int:pk>', views.PerfilDeleteView.as_view(), name='delete'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ProdutoList.as_view(), name='lista'),
    path('<slug>', views.ProdutoDetalhes.as_view(), name='produtoDetalhes'),
    path('ProdutoAddToCar/', views.ProdutoAddToCar.as_view(), name='produtoAddToCar'),
    path('ProdutoRemoverFromCar/', views.ProdutoRemoverFromCar.as_view(),
         name='produtoRemoverFromCar'),
    path('Cart/', views.Cart.as_view(), name='cart'),
    path('Resumo/', views.Resumo.as_view(), name='resumo'),
]

produto/models.py
import os
from django.db import models
from PIL import Image
from django.conf import settings
from django.utils.text import slugify
from utils import utils


class Produto(models.Model):
    name = models.CharField(max_length=50)
    cut_description = models.TextField(max_length=500)
    long_description = models.TextField(max_length=2000)
    image = models.ImageField(
        upload_to='produto_img/%Y/%m', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='preco')
    preco_marketing_promo = models.FloatField(
        default=0, verbose_name='preco_promo')
    tipo = models.CharField(
        max_length=1,
        default='V',
        choices=(
            ('V', 'Variavel'),
            ('S', 'Simples'),
        )
    )

    class Meta:
        verbose_name = ("Produto")
        verbose_name_plural = ("Produtos")

    def get_preco_formatado(self):
        return utils.filter_price(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'

    def get_preco_formatado_promo(self):
        return utils.filter_price(self.preco_marketing_promo)
    get_preco_formatado_promo.short_description = 'Preço_Promo'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Produto_detail", kwargs={"pk": self.pk})

    @ staticmethod
    def resize_image(img, new_width):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        print(original_width, new_width)
        # valida o tamnho da imagem
        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)
        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}'
            self.slug = slug

        super().save(*args, **kwargs)  # Call the real save() method
        max_image_size = 500

        if self.image:
            self.resize_image(self.image, max_image_size)


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_marketing = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = ("Variacao")
        verbose_name_plural = ("Variacaos")

    def __str__(self):
        return self.nome or self.produto.name

    def get_absolute_url(self):
        return reverse("Variacao_detail", kwargs={"pk": self.pk})

produto/views.py
from django.http import HttpResponse
from pprint import pprint

from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages
from .models import Produto, Variacao
from perfil.models import Perfil


class ProdutoList(ListView):
    model = Produto
    template_name = 'produto/produto_list.html'
    context_object_name = 'produtos'
    paginate_by = 6


class ProdutoDetalhes(DetailView):
    model = Produto
    template_name = 'produto/produto_details.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class ProdutoAddToCar(View):

    def get(self, *args, **kwargs):

        # limpa o carinho
        # if self.request.session.get('carrinho'):
        #     del self.request.session['carrinho']
        #     self.request.session.save()

        http_referer = self.request.META.get(
            'HTTP_referer',
            reverse('produto:lista')
        )
        # converti devido a dar erro na jora de remover não encontrarva o id no diccionário
        variacao_id = int(self.request.GET.get('vid'))

        if not variacao_id:
            messages.error(
                self.request, f'Produto não encontrado!!!'
            )
            # pega a pagina que o usuario estava anteriormente
            return redirect(http_referer)

        variacao = get_object_or_404(Variacao, id=variacao_id)
        produto = variacao.produto

        produto_id = produto.id
        produto_nome = produto.name
        variacao_nome = variacao.nome
        # variacao_id = variacao.id
        preco_unitario = variacao.preco or ''
        preco_unitario_promocional = variacao.preco_marketing or ''
        quantidade = 1
        slug = produto.slug
        imagem = produto.image

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Produto Esgotado!!!'
            )
            return redirect(http_referer)

    ################# SESSOIONS #######################
        # criando sessões para guardar os dados
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session.get('carrinho')

        if variacao_id in carrinho:
            # variacao existe no carrinho
            # obtem quantidade da chave variacao_id
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao.estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Estoque do produto Esgotado!!! {variacao.estoque} {produto.name} adicionados no carrinho'
                )
                return redirect(http_referer)
                # caso a qtd compra seja maior do disponivel em estoque ele adiona a quantidade do estque no carrinho
                # quantidade_carrinho = variacao.estoque
            # atualiza a qtd do valor no dicionario. EX: 1{'quantidade': 'quantidade_carrinho'} /// 1{'quantidade': 4}
            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = quantidade_carrinho * preco_unitario
            carrinho[variacao_id]['preco_quantitativo_promocional'] = quantidade_carrinho * \
                preco_unitario_promocional

        else:
            # variacao NÃO existe no carrinho
            carrinho[variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome,
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_quantitativo':  preco_unitario,
                'preco_unitario_promocional': preco_unitario_promocional,
                'preco_quantitativo_promocional': preco_unitario_promocional,
                'quantidade': quantidade,
                'slug': slug,
                'imagem': imagem,
            }
        self.request.session.save()

        # pprint(carrinho)
        messages.success(
            self.request,
            f'Produto {produto.slug} {variacao.nome} adicionado ao carrrinho'
        )
        return redirect(http_referer)


class ProdutoRemoverFromCar(View):
    def get(self, *args, **kwargs):
        http_refer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:produtoRemoverFromCar')
        )

        variacao_id = self.request.GET.get('vid')

        # when user access from copy/past url
        if not variacao_id:
            return redirect(http_refer)

        # when not itens in sesssion cart
        if not self.request.session.get('carrinho'):
            return redirect(http_refer)

        # when key not exists in dict carrinho
        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_refer)

        carrinho = self.request.session['carrinho'][variacao_id]

        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        messages.success(
            self.request, f'Produto {carrinho["produto_nome"]} removido')
        return redirect(http_refer)


class Cart(View):
    def get(self, *args, **kwargs):
        template = 'produto/cart.html'
        return render(self.request, template)


class Resumo(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:insert')

        perfil = Perfil.objects.filter(usuario=self.request.user).exists()

        if not perfil:
            messages.error(
                self.request,
                'Usuário sem perfil.'
            )
            return redirect('perfil:insert')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio.'
            )
            return redirect('produto:lista')

        contexto = {
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
        }

        return render(self.request, 'produto/resumodacompra.html', contexto)

produto/templates/produto/cart.html
{% extends "base.html" %}

{% block 'content' %}
{% load static %}

{% load omfilters %}

{% if request.session.carrinho %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
        {% include 'partials/_carrinho.html' %}
    </div>
</div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>{{request.session.carrinho|cart_totals|filter_price}} </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">
        <a class="btn btn-lg btn-block btn-primary" href=" {% url 'produto:resumo'%}">
            Finalizar a compra
        </a>
    </div>
</div>

<!-- {{request.session.carrinho}} -->
{% else %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Não há itens no carrinho.</p>
    </div>
</div>
{% endif %}
{% endblock 'content' %}

produto/templates/produto/produto_details.html
{% extends "base.html" %}
{% load omfilters %}

{% block 'title' %}Detalhes|{{produto.name}} {% endblock 'title' %}
{% block 'content' %}
<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if produto.image %}
                <img class="img-fluid" src="{{produto.image.url}}" alt="{{produto.name}} ">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2"> {{produto.name}} </h1>
            <p class="lead">{{produto.cut_description}} </p>
            <p class="lead">
                {% if produto.preco_marketing_promo and produto.preco_marketing_promo != produto.preco_marketing %}
                <span id="variation-preco-promocional" class="lead product-price">
                    {{produto.preco_marketing_promo|filter_price}}
                </span>
                <span id="variation-preco" class="lead product-old-price">
                    {{produto.preco_marketing|filter_price}}
                </span>
                {% else %}
                <span id="variation-preco" class="lead product-price">{{produto.preco_marketing|filter_price}} </span>
                {% endif %}
            </p>

            <form action=" {% url 'produto:produtoAddToCar' %} " id="form-add-to-cart">
                <div class="form-group">
                    {% if produto.variacao_set.all %}
                    <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                        {% for variacao in produto.variacao_set.all %}

                        {% if variacao.preco_marketing %}
                        <option data-preco=" {{variacao.preco|filter_price}} "
                            data-preco-promocional="{{variacao.preco_marketing|filter_price}} "
                            value=" {{variacao.id}} ">
                            {{variacao.nome}}
                        </option>
                        {% endif %}
                        {% endfor %}
                    </select>
                    {% endif %}
                </div>

                <div class="text-left">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Adicionar ao carrinho
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{produto.name}} </h2>
            {{produto.long_description|linebreaks}}
        </div>
    </div>
</div>


{% endblock 'content' %}

produto/templates/produto/produto_list.html
{% extends "base.html" %}

{% load omfilters %}

{% block 'title' %}Lista Produtos{% endblock 'title' %}]

{% block 'content' %}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for p in produtos %}
            <div class="card">
                {% if p.image %}
                <a href="{{p.slug}}">
                    <img class="card-img-top" src="{{p.image.url}} " alt="{{p.name}} ">
                </a>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{p.name}} </h5>
                    <p class="card-text"> {{p.cut_description}} </p>
                    <div class="container product-price-block text-center">
                        {% if p.preco_marketing_promo and p.preco_marketing_promo != p.preco_marketing %}
                        <span class="product-price">
                            {{p.preco_marketing_promo|filter_price}}
                        </span>
                        <span class="product-old-price text-muted">
                            {{p.preco_marketing|filter_price}}
                        </span>
                        {%else%}
                        <span class="product-price">
                            {{p.preco_marketing|filter_price}}
                        </span>
                        {% endif %}


                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{{p.slug}}" class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "partials/_pagination.html" %}

{% endblock %}

produto/templates/produto/resumodacompra.html
{% extends 'base.html' %}
{% load omfilters %}

<!-- {% block titulo %}Resumo da compra | {% endblock %} -->

{% block 'content' %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'perfil:insert' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ usuario.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ usuario.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.idade }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.data_nascimento }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ usuario.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'perfil:insert' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.endereco }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.numero }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.complemento }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.bairro }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cidade }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.estado }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cep }}</dd>
        </dl>
    </div>
</div>



<div class="row mt-3">
    <div class="col">
        <h3>Resumo do carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'partials/_carrinho.html' %}
    </div>

</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center"><span class="font-weight-bold">Total do carrinho:</span>
            {{ carrinho|cart_totals }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'pedido:pagar' %}">
            Continuar
        </a>
    </div>
</div>


{% endblock %}